
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Cos1Test extends E2eTestBase {

  public Cos1Test() {
    coreCodeTemplate = "a = 0\ninc = TWO_PI/25\nfor (i in 0:24) {\n    line(i * 4, 50, i * 4, 50 + cos(a) * 40)\n    a = a + inc\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/cos_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
